apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-ekopro-distributor
  description: Tanzu Ekopro dystrybutor test
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=tanzu-ekopro-distributor'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
